# Путь к файлу: models/marts/schema.yml

version: 2

models:
  - name: shipping_dim
    columns:
      - name: ship_id
        tests:
          - unique
          - not_null

  - name: customer_dim
    columns:
      - name: cust_id
        tests:
          - unique
          - not_null

  - name: geo_dim
    columns:
      - name: geo_id
        tests:
          - unique
          - not_null

  - name: product_dim
    columns:
      - name: prod_id
        tests:
          - unique
          - not_null

  - name: sales_fact
    columns:
      - name: cust_id
        tests:
          - relationships:
              arguments:  
                to: ref('customer_dim')
                field: cust_id

  - name: mart_monthly_sales
    columns:
      - name: total_sales
        tests:
          - not_null
          - is_positive # <-- Наш кастомный тест

      - name: number_of_orders
        tests:
          - is_positive
    
  - name: mart_monthly_running_profit
    description: "Агрегированная витрина, показывающая ежемесячную прибыль и совокупную прибыль нарастающим итогом"
    columns:
      - name: monthly_profit
        description: "Прибыль за месяц"
        tests:
          - not_null
          - is_positive

      - name: cumulative_profit
        description: "Совокупная прибыль нарастающим итогом"
        tests:
          - not_null
          - is_positive
